version: 2.1

orbs:
  ecspresso: fujiwara/ecspresso@2.0.3

jobs:
  install:
    docker:
      - image: cimg/base:2022.12
    steps:
      - checkout
      - ecspresso2.0.3/install:
          version: latest
      - run:
          command: |
            ecspresso version | fgrep v2.
      - ecspresso2.0.3/install:
          version: v1.7.15
      - run:
          command: |
            ecspresso version | fgrep v1.7.15
      - ecspresso2.0.3/install:
          version-file: .ecspresso-version
      - run:
          command: |
            ecspresso version | fgrep v2.0.0

workflows:
  version: 2
  deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - main
